"""empty message

Revision ID: 2650c4bcbe2d
Revises: 9a7aa0f910d5
Create Date: 2020-03-19 10:55:15.961990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2650c4bcbe2d'
down_revision = '9a7aa0f910d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists_genres')
    # ### end Alembic commands ###
