"""empty message

Revision ID: 6025c2da07c6
Revises: cf0174187af7
Create Date: 2020-04-01 12:34:14.289880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6025c2da07c6'
down_revision = 'cf0174187af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_genres_genre_id_fkey', 'artists_genres', type_='foreignkey')
    op.drop_constraint('artists_genres_artist_id_fkey', 'artists_genres', type_='foreignkey')
    op.create_foreign_key(None, 'artists_genres', 'artists', ['artist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'artists_genres', 'genres', ['genre_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists_genres', type_='foreignkey')
    op.drop_constraint(None, 'artists_genres', type_='foreignkey')
    op.create_foreign_key('artists_genres_artist_id_fkey', 'artists_genres', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key('artists_genres_genre_id_fkey', 'artists_genres', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
