"""empty message

Revision ID: 6fd6ed878b88
Revises: aeb746dd6843
Create Date: 2020-03-12 16:00:23.910635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd6ed878b88'
down_revision = 'aeb746dd6843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('website_link', sa.String(length=120), server_default='', nullable=False),
    sa.Column('facebook_link', sa.String(length=120), server_default='', nullable=False),
    sa.Column('seeking_venue', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('seeking_description', sa.String(length=500), server_default='', nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    # ### end Alembic commands ###
