"""empty message

Revision ID: 710f231a1548
Revises: 7ddcae042fdc
Create Date: 2020-04-25 20:46:48.067745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "710f231a1548"
down_revision = "7ddcae042fdc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "venues", "facebook_link", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "venues",
        "image_link",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_server_default=sa.text(
            "'https://images.all-free-download.com/images/graphiclarge/scene_layout_04_hd_picture_167802.jpg'::character varying"
        ),
    )
    op.alter_column(
        "venues",
        "seeking_description",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "venues", "website_link", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "venues",
        "website_link",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "venues",
        "seeking_description",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "venues",
        "image_link",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_server_default=sa.text(
            "'https://images.all-free-download.com/images/graphiclarge/scene_layout_04_hd_picture_167802.jpg'::character varying"
        ),
    )
    op.alter_column(
        "venues",
        "facebook_link",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###
