"""empty message

Revision ID: 7ddcae042fdc
Revises: 90811f46e42a
Create Date: 2020-04-25 20:35:30.738708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ddcae042fdc"
down_revision = "90811f46e42a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artists",
        "facebook_link",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "artists",
        "image_link",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_server_default=sa.text(
            "'http://images.pexels.com/photos/14166/pexels-photo-14166.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260'::character varying"
        ),
    )
    op.alter_column(
        "artists",
        "seeking_description",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "artists",
        "website_link",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artists",
        "website_link",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "artists",
        "seeking_description",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "artists",
        "image_link",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_server_default=sa.text(
            "'http://images.pexels.com/photos/14166/pexels-photo-14166.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260'::character varying"
        ),
    )
    op.alter_column(
        "artists",
        "facebook_link",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###
