"""Initial migration.

Revision ID: acb89e42b844
Revises: 
Create Date: 2020-04-25 23:24:36.048195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acb89e42b844"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=120), nullable=False),
        sa.Column("website_link", sa.String(length=120), nullable=True),
        sa.Column("facebook_link", sa.String(length=120), nullable=True),
        sa.Column(
            "seeking_venue", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("seeking_description", sa.String(length=500), nullable=True),
        sa.Column(
            "image_link",
            sa.String(length=500),
            server_default="http://images.pexels.com/photos/14166/pexels-photo-14166.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    genres_table = op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("address", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=120), nullable=False),
        sa.Column("website_link", sa.String(length=120), nullable=True),
        sa.Column("facebook_link", sa.String(length=120), nullable=True),
        sa.Column(
            "seeking_talent", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("seeking_description", sa.String(length=500), nullable=True),
        sa.Column(
            "image_link",
            sa.String(length=500),
            server_default="https://images.all-free-download.com/images/graphiclarge/scene_layout_04_hd_picture_167802.jpg",
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artists_genres",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="cascade"),
    )
    op.create_table(
        "shows",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("artist_id", "venue_id", "start_time"),
    )
    op.create_table(
        "venues_genres",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="cascade"),
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        genres_table,
        [
            {"name": "Alternative"},
            {"name": "Blues"},
            {"name": "Classical"},
            {"name": "Country"},
            {"name": "Electronic"},
            {"name": "Folk"},
            {"name": "Funk"},
            {"name": "Heavy Metal"},
            {"name": "Instrumental"},
            {"name": "Jazz"},
            {"name": "Latin"},
            {"name": "Musical Theater"},
            {"name": "Pop"},
            {"name": "Punk"},
            {"name": "R&B"},
            {"name": "Reggae"},
            {"name": "Rock"},
            {"name": "Soul"},
            {"name": "Hip-Hop"},
            {"name": "Swing"},
            {"name": "Other"},
            {"name": "Reggaeton"},
            {"name": "Merengue"},
            {"name": "Salsa"},
            {"name": "Lounge"},
            {"name": "Trap"},
            {"name": "Rap"},
            {"name": "Dubstep"},
            {"name": "Kpop"},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venues_genres")
    op.drop_table("shows")
    op.drop_table("artists_genres")
    op.drop_table("venues")
    op.drop_table("genres")
    op.drop_table("artists")
    # ### end Alembic commands ###
