"""empty message

Revision ID: cf0174187af7
Revises: 9fd6254ecb4c
Create Date: 2020-03-31 16:14:09.105144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0174187af7'
down_revision = '9fd6254ecb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venues_genres_venue_id_fkey', 'venues_genres', type_='foreignkey')
    op.drop_constraint('venues_genres_genre_id_fkey', 'venues_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venues_genres', 'genres', ['genre_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'venues_genres', 'venues', ['venue_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues_genres', type_='foreignkey')
    op.drop_constraint(None, 'venues_genres', type_='foreignkey')
    op.create_foreign_key('venues_genres_genre_id_fkey', 'venues_genres', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key('venues_genres_venue_id_fkey', 'venues_genres', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###
